repos:
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        name: Markdown Lint
        description: Lint newly changed Markdown files
        entry: mdl
        args: ["--ignore-front-matter", "--style", ".mdl_style.rb"]
        language: ruby
        files: "^(content|README.md)"

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.3
    hooks:
      - id: markdown-link-check
        name: Markdown Link Check
        description: Check links in newly changed Markdown files
        entry: markdown-link-check
        args: ["--config", "mlc_config.json"]
        language: node
        files: "^(content|README.md)"

  - repo: local
    hooks:
      - id: hugo
        name: Build pages with Hugo
        description: Build pages with Hugo
        language: system
        entry: hugo --minify
        pass_filenames: false
