repos:
  - repo: https://github.com/markdownlint/markdownlint
    # v0.11.0 is specifically used here as later versions of the `mdl` gem are
    # incompatible with the macOS system Ruby version (2.6) and thus require
    # extra steps to ensure that a newer Ruby version is installed.
    rev: v0.11.0
    hooks:
      - id: markdownlint
        name: Markdown Lint
        description: Lint newly changed Markdown files
        entry: mdl
        exclude: '.github/'
        language: ruby
        types: ["markdown"]

  - repo: local
    hooks:
      - id: hugo
        name: Build pages with Hugo
        description: Build pages with Hugo
        language: system
        entry: hugo --minify
        pass_filenames: false
