# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: check-json
    -   id: pretty-format-json
        args: [--no-ensure-ascii, --no-sort-keys, --autofix]
        files: ".+json"
    -   id: check-added-large-files
# - repo: https://github.com/jumanjihouse/pre-commit-hooks
#   rev: master  # or specific git tag
#   hooks:
#     - id: markdownlint # Configure in .mdlrc
#       files: "content/"
