blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/alan-turing-institute/REG-handbook/discussions
    about: Would your comment/question/suggestion be better suited to a discussion?
