---
name: CI

on: [push]

jobs:
  markdown_lint:
    name: "Lint Markdown"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head

      - name: Install mdl
        run: gem install mdl

      - name: Lint markdown
        run: mdl --ignore-front-matter --style .mdl_style.rb ./

  markdown_link_check:
    name: "Check Markdown links"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          use-verbose-mode: "yes"

  hugo:
    name: "Hugo build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

  html-proofer-internal-links:
    name: "HTML proofer internal links"
    runs-on: ubuntu-latest
    needs: hugo

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head

      - name: Install html-proofer
        run: gem install html-proofer

      - name: Build
        run: hugo --minify

      - name: Run html-proofer
        # swap URLs
        # - adjust for base URL (REG-handbook)
        # Ignore internal links to base URL
        # Only check internal links
        run: |
          htmlproofer ./public \
          --check-favicon \
          --check-html \
          --check-img-http \
          --disable-external \
          --url-swap "^/REG-handbook/:/" \
          --url-ignore '/REG-handbook'

  html-proofer-external-links:
    name: "HTML proofer external links"
    runs-on: ubuntu-latest
    needs: hugo

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Install html-proofer
        run: gem install html-proofer

      - name: Build
        run: hugo --minify

      - name: Run html-proofer
        # swap URLs
        # - adjust for internal links with fqdn (https://alan-turing-institute.github.io/REG-handbook)
        # - Adjust edit and tree paths on GitHub to current branch (*/edit/main, */tree/main)
        # Only check external links
        run: |
          htmlproofer ./public \
          --check-favicon \
          --check-html \
          --check-img-http \
          --enforce-https \
          --external-only \
          --url-swap "^^https\://alan-turing-institute.github.io/REG-handbook/:/,/edit/main:/edit/$(git branch --show-current),/tree/main:/tree/$(git branch --show-current)" \
