---
name: CI

on: [push, pull_request]

jobs:
  markdown_lint:
    name: "Lint Markdown"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Install mdl
        run: gem install mdl

      - name: Lint markdown
        run: mdl --ignore-front-matter --style .mdl_style.rb ./

  markdown_link_check:
    name: "Check Markdown links"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          use-verbose-mode: "yes"

  hugo:
    name: "Hugo build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
