---
name: Content Quality

on: [push]

jobs:
  content_age:
    name: "Content Age"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install tabulate
      - name: Run script
        run: .github/scripts/content_age.py
  prose_lint:
    name: "Prose Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install proselint
      - name: Run proselint
        run: proselint ./content | tee
